name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # LTS
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Check Formatting
        run: npm run format:verify
      #- name: Lint
      #  run: npm run lint:verify
      #- name: Test
      #  run: npm run test
      - name: Build
        run: npm run build
